.MODEL SMALL
.STACK 100H
.DATA
CR EQU 0DH
LF EQU 0AH
MAJOR DB '?'
MINOR DB '?'
MSG DB 'GET DOS VERSION:INT 21H FUNCTION 3OH',CR,LF,'MS-DOS Version ,$'
MSG1 DB CR,LF,'MAJOR VERSION NUMBER IS :$'
MSG2 DB CR,LF,'MINOR VERSION NUMBER IS :$'
.CODE
MAIN PROC
;initialization
MOV AX,@DATA
MOV DS,AX
;get dos version
MOV AH,30H
INT 21H
MOV MAJOR,AL
MOV MINOR ,AH
;display results
LEA DX,MSG
MOV AH,9h
INT 21H
LEA DX,MSG1
MOV AH,9h
INT 21H
XOR AX,AX
MOV AL,MAJOR
CALL OUTDEC
LEA DX,MSG2
MOV AH,9h
INT 21H
XOR AX,AX
MOV AL,MINOR
CALL OUTDEC
;return to dos
MOV AH,4CH
INT 21H
MAIN ENDP
Include DES_NUM.asm
END MAIN